name: Gruppe 6 Discord Bot

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    # Redémarrage automatique toutes les 6h pour éviter les timeouts
    - cron: '0 */6 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Discord Bot
        env:
          BOT_TOKEN: ${{ secrets.MTIyNTEyOTcxOTc0NjUyNzIzMg.G8nq-Q.q_UPPJlsV8oENubVvYhBGXBX23aBeyeSj4r4z8 }}
          WEBAPP_URL: ${{ secrets.https://script.google.com/macros/s/AKfycbwtA_t9Z4BEjr7oN_SegKBtwMuMQ4dGFa4jvz-UABjpkzWGLZ524GM9wWeDMHBFXakR/exec }}
          CHANNEL_ID: "1498184266045984881"
        run: node bot.js
